### ISSUE TITLE
Feature: User can search for games

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for games

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to type into the search bar a game that they want to look up and a list of related results will show up.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106632915/190234651-9cd34677-b365-4f6e-9653-e7deeac2f443.png)

![image](https://user-images.githubusercontent.com/106632915/190234779-cc919bac-5411-4f1d-a4fa-4ad3a217565c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ... the exported file on dbdesigner (take out public in the schema")

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... deal with a get request to the api to get the search results send them back from the server. 
- [x] since my api has an 0auth and an expiration time on the token.  will have to deal with refreshing the token on expiration.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ... display the navbar
- [x] in the navbar component there should be an input for the search.
- [x] in that search form, there should be an event listener to handle searches.
- [x] there should be a handleSearch method that is passed down from app.jsx which is called on the event listner
- [x] this method should make the appropriate request to the server and get back a response.
- [x] this should call setstate to change the value of games property which would be used to rerender the page with the search results page.
- [x] create a component to... create a container for the different pages
- [x] Create a page component to ... display the searched results when a search is made.
- [x] create a render page method that shows the appropriate page.  In this scenario since the games property
of this.state is no longer empty make a conditional that reflects this change and shows the results page.
- [x] pass the game data from the search method as a prop to the search results page
- [x] render the search results page with the appropriate styling.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
