### ISSUE TITLE
Design Update:  User can see pages for search results and comments

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#17]
## ⚙️ Feature

> ##### Which feature is affected by this update?

## 📐 Plan

> ##### Summary of the technical approach to be taken.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![image](https://user-images.githubusercontent.com/106632915/191612884-4c1d5e9e-cc2f-4f9c-a299-297b188ea692.png)
![image](https://user-images.githubusercontent.com/106632915/191613005-97795dfa-364a-4a64-8a16-a870f2a26164.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] ...create a pagination component.
- [ ] the pagionation anchors should have an onclick handler to change the state of property of currentpage.
- [ ] create properties of current page, posts perpage.  use these to slice the appropriate page from the listofGames array.
- [ ] pass the sliced array down to the searches component.
- [ ] style accordingly
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
