### ISSUE TITLE
Feature: User can view details of game

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of a specific game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After searching for their game, user will be able to click on the cover image of the game to look at the details.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/106632915/189720231-5328fdb5-f7eb-4632-9b0a-96b86bbc51ac.png">

<img width="224" alt="image" src="https://user-images.githubusercontent.com/106632915/189720022-2bfc1d81-b8bc-44b6-b4dd-f8e53967c6e8.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... to deal with a get request for that specific game
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a page component called game details.
- [x] this page should render on click of the anchor image on the search results page due to the hashchange which rerenders the page.
- [x] Will  need to set a prop for the game id to pass down from the href.#games?gameId=1234.
- [x] the page details component will make the fetch request using the prop that was passed down on component did mount.
- [ ] style page appropriately.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
