### ISSUE TITLE
Design Update: User can make half star ratings 4.5/5

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#21]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can review a game and leave a half star rating, such as 4.5 stars / 5.

## 📐 Plan

> ##### Summary of the technical approach to be taken.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/106632915/192024675-ffa46880-f6e7-40a7-9a5a-4b4407c322d7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Update starRating component to map over 10 items in an array.
- [ ] I will have to use overflow:hidden and make the container for the star only show half of the star.  That way i will have 10 stars, but each one will only show half.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
