### ISSUE TITLE
Feature: User can edit their profile.

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#23]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can change their username and profile picture.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106632915/192063331-b5baeac6-e0e2-4ad0-bb61-f5c830c6c79f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ... have a profile picture url as a row.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ... deal with a get request of the user username and profile picture.
- [ ] will have to make a post request to deal with entering the new url and username if applicable.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a page component to ... show username and profile picture.
- [ ] The page component on click of the edit profile button would cause a rerender of the page
- [ ] this would display the edit profile page instead of the base profile page.
- [ ] create a handlesubmit that lets sends the new information to the server which updates the sqldatabase.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
