### ISSUE TITLE
Feature: User can comment on a game

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can comment on a game.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click the + to add a new comment to the game details page they are viewing.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/106632915/190482897-1414c953-345b-4dbc-a782-8397fdff6d22.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/106632915/190482998-102d772a-f7ed-4814-b196-497bcabcfaf8.png">

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/106632915/190483175-5b9a9cf7-9413-4dba-83fc-bf1806ceb999.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... deal with a post request that updates inserts information into our comments table in our sql database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] create a form in the comments section that has a text area.
- [x] create a handlechange function that updates the state of the comment.
- [x] create a handle submit function that handles the submit and calls the fetch function
- [x] the fetch function will tell the server to update the table in sql.
- [x] it will then return the comment which we will use to update the state of our this.state.comments.
- [ ] create a componentdidupdate function that notices component that the comments state has updated which will rerender teh details page.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
