### ISSUE TITLE
Feature: User can rate a game

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can rate a game

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to optionally add a rating to the game in the comments by clicking the stars.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/106632915/190706181-d3f89ce7-6035-4593-86bc-2f8818ec81eb.png">
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/106632915/190706240-ab20317d-c216-41d9-9814-5e23ea23c40f.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... deal with a post request to post a new rating on the "ratings" table on the database at the same time as updating the comments table after a submit occurs.  Use promise all to return the new results?
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] create a clickable star feature that toggles the ratings from 1 star to 5 stars.
- [ ] create a the star rating display the top.
- [x] add this clickable feature to the comments drop down.
- [x] create an onclick handler for the star that sets the state for the star rating based on index maybe?
- [x] update the promises of the handlesubmit event to change the state of the star rating.
- [ ] the newly made comment should have a star rating when posted on the page next to the username.
- [ ] Will need to update the  get request on the details page to handle updating the ratings at the top on mount, if 
a rating already exists on the database.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
