### ISSUE TITLE
Feature: User can log in

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to log in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to type into the username and password input fields and then press the log in button to log into their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106632915/191333818-57e26b65-9290-4d86-af77-510e4266fdff.png)
![image](https://user-images.githubusercontent.com/106632915/191334022-6345d0d4-6f14-4aaa-be64-7e789bd205cb.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... deal with a a post request to the server which will send back a payload and a token.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a method for handlesign in, this will save the token to local storage and re render the page by reassigning the value for the user property.
- [x] update handlesubmit method in authform component to call handlesign in method if user and token are truthy.
- [x] update component did mount on app.jsx to set the user value to the decoded token or null.  call setstate for to rerender the page for new values of user and isAuthorizing.
- [x] style log in page accordingly.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
