### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click the have an account anchor or the sign up buton at the top right drawer to create an account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/106632915/191108909-ced27711-21c3-4d23-a85c-91b660e0a7b8.png">
<img width="256" alt="image" src="https://user-images.githubusercontent.com/106632915/191109090-d41bf178-1dd0-4262-968b-4ac04d0f7f97.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... create a handler for the route of signing up.  This route should make a
post request to the server to insert a new user into the users table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ... display the auth page
- [x] The auth page should redirect to the home page,, it should also show the appropriate auth form using the auth form component.
- [x] Create a component to show the appropriate auth form.
- [x] The authform component will display sign up form.  This will have the handlesubmit method to handle the creation of a new user.
- [x] assign a new hash to the window.location that will send the user to the either the sign in page or the home page.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
