### ISSUE TITLE
Feature: User can log out

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log out

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click log out from the top drawer to log out.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/106632915/191870324-8588d7cd-ca54-41fd-944d-a2f385684154.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] create a javascript expression that shows sign in and sign up if user === null and
or log out if user !== null.
- [ ] if user !== null, create a button with an onClick listener for handlesignout.
- [ ] this button should call the passed down prop of the handlesignout method.  This will remove the item from local storage as well as setstate of user back to null.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
