### ISSUE TITLE
Feature: User can can play videos of the game

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/mist#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can play videos of the game

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can a click video in the game details page and once clicked, a modal will popout with the video.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106632915/189725208-3f013403-feb0-42dc-bced-36b84f2f5c4b.png)
![image](https://user-images.githubusercontent.com/106632915/189725310-42aa7440-9596-4d61-a481-49cb67ed73f8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Create a modal that appears on click of the img. Modal should be fixed and have a black overlay.
- [ ] this modal should have an iframe that can play the youtube video.  
- [ ] modal should be sized differently for mobile window etc.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
